export const SliderData = [
  {
    image:
      'https://ne-campground-reviews.s3.amazonaws.com/bear-brook/bearbrook-1.jpg'
  },
  {
    image:
      'https://ne-campground-reviews.s3.amazonaws.com/bear-brook/bearbrook-2.jpg'
  },
  {
    image:
      'https://ne-campground-reviews.s3.amazonaws.com/bear-brook/bearbrook-3.jpg'
  },
  {
    image:
      'https://ne-campground-reviews.s3.amazonaws.com/bear-brook/bearbrook-4.jpg'
  },
  {
    image:
      'https://ne-campground-reviews.s3.amazonaws.com/bear-brook/bearbrook-5.jpg'
  }
];